name: style_transfer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.0.17
  image_picker: ^0.8.8
  tflite_flutter:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
    - assets/styles/

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
